### ISSUE TITLE
[Bug] Exception thrown in query parameters validation

### ISSUE THREAD

**Issue by gsikorski** [nawaz1991/cpp-oasvalidator#14]
[empty-query-validation.patch](https://github.com/nawaz1991/cpp-oasvalidator/files/14039629/empty-query-validation.patch)
**Describe the bug**
Program throws when trying to parse a path with no query parameters and a single (potentially optional) query parameter is present in the schema.

**To Reproduce**
Define schema with any path with single query parameter (may be optional as below):
```json
        "parameters": [
          {
            "name": "limit",
            "in": "query",
            "description": "How many items to return at one time (max 100)",
            "required": false,
            "schema": {
              "type": "integer",
              "maximum": 100,
              "format": "int32"
            }
          }
        ],
```
Try to validate a path with no parameters.

The program throws in `ValidatorsStore::ValidateQueryParams:61` [std::string::at](https://en.cppreference.com/w/cpp/string/basic_string/at).

**Expected behavior**
Validation passes (or fails with `ValidationError::INVALID_QUERY_PARAM` error if the query parameter is required).

**Desktop (please complete the following information):**
Any

I attach a possible bugfix.

**Comment by nawaz1991** [comment]
@gsikorski , thank for your interest in cpp-oasvaldiator and helping to fix it. Please give a star, if you find this library useful.
Please also have a look at the related projects like lua-oavaldiator, kong-plugin-oasvalidator etc.
https://github.com/nawaz1991?tab=repositories
