### ISSUE TITLE
[Feature] Option to check HEAD requests against GET API definition

### ISSUE THREAD

**Issue by sic-poths** [nawaz1991/cpp-oasvalidator#27]
**Is your feature request related to a problem? Please describe.**
If I understand it correctly the validations very closely checks that the HTTP Verb matches exactly the one in the API definition. For a HEAD request I think this is strange, as common practice seems to be to only document the GET-Endpoint and allow HEAD requests for the same resource that will just not return the body of the response.

**Describe the solution you'd like**
If my observation above is valid, it would be nice to allow HEAD requests for all ducmented GET requests. 
This could be enabled by default in my opinion, but it would also be sufficiant to have a setting that allows for this behaviour.

**Describe alternatives you've considered**
Our current alternative is to define a HEAD endpoint additionally to _each_ GET endpoint in our OpenAPI specification before setting it up in our Kong API-GW that has the oasvalidator plugin activated.

Thank you for your consideration!

**Comment by nawaz1991** [comment]
@sic-poths , your requirement for the feature is fullfilled for the base project https://github.com/nawaz1991/cpp-oasvalidator and I will update https://github.com/nawaz1991/lua-oasvalidator as well and upload the module on luarocks soon.
Here is how it is fulfilled:
I have added an optional arg for cpp-oasvalidator intialization as:
```C++
method_map = {
     {"OPTIONS", {"GET", "POST", "PUT", "DELETE", "HEAD", "PATCH"}},
     {"HEAD", {"GET"}} // Treat HEAD request as GET
     // so on
     };
```
So, to treat `GET` requests as `HEAD`, you can provide:
```C++
method_map = {
     {"HEAD", {"GET"}} // Treat HEAD request as GET
     };
OASValidator validator(oas_specs, method_map);
```
Similarly, in lua, I will add support for optional table for mapping.

**Comment by nawaz1991** [comment]
@sic-poths , version 1.1.0 of Lua osavlidator is released, https://luarocks.org/modules/nawaz1991/oasvalidator, please try it out. 
You need to provide `method_map` like

```lua
oasvalidator = require("oasvalidator")

method_map = {
     {"HEAD", {"GET"}} // Treat HEAD request as GET
     };
OASValidator validator(path/to/specs.json, method_map);
```

Please give star to my repos, if you think it the project is worth it:
https://github.com/nawaz1991/cpp-oasvalidator
https://github.com/nawaz1991/lua-oasvalidator
https://github.com/nawaz1991/kong-plugin-oasvalidator

Note, kong plugin needs to be updated, I will be doing it soon.
